### ISSUE TITLE
Code inlining and jvm-target

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#81]
I just encountered the following error:

> Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8

Obviously, the kernel uses JVM 8 as a target and if the library targets 11, there will be problems with inlining. There are several ways to address the problem. There could be a switch in the configuration, or it could use current JDK target as default or both.

**Comment by ileasile** [comment]
What are you trying to do? We have a gradle option to change a target for kernel (see #39), will it help you if the kernel will be built with 11 target?

**Comment by altavir** [comment]
I tried to use a library with inline methods which were built with jvmTarget="11". Now I understand that it is not a simple problem, we usually can't control the target of libraries we use in the notebook and it is quite possible that some of those will be built with different targets.

**Comment by altavir** [comment]
![image](https://user-images.githubusercontent.com/9514268/84058761-5ac79400-a9c2-11ea-96e5-1d1f0e63900c.png)
I've explicitly checked that the java version is 11. This version of plotly.kt is built with `jvmTarget ="11"`.

**Comment by ileasile** [comment]
Could you please share your notebook (here or in JB Slack direct messages)? I think I know where this error goes from, need to check it.

**Comment by ileasile** [comment]
Could you please try kernel version (from dev channel) `0.8.1.40.dev7`?

**Comment by altavir** [comment]
It works for 0.8.1.40.dev7

**Comment by ileasile** [comment]
I've added a possibility to assert version in the notebook like that:
```
JavaRuntimeUtils.assertVersionAtLeast(11)
```

More version utils are available via `JavaRuntimeUtils` object.

Also, JVM target for snippets is now set to current JRE version. So, the issue should be fixed now.

**Comment by phiSgr** [comment]
> Also, JVM target for snippets is now set to current JRE version. So, the issue should be fixed now.

Can it be `currentJavaVersion.coerceAtMost(max of JvmTarget supported by compiler)`?

If I run Kotlin Jupyter on Java 22, JVM target 22 (class file version 66) is unsupported by current Kotlin compiler, so it defaults to 1.8. And I will still get `Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option`
